name: "Terraform End 2 End Workflow"

on:
  workflow_call:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Checkout
        uses: actions/checkout@main

      - name: Prepare Terraform
        uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: ${{ secrets.TERRAFORM_VERSION }}
            cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_WORKSPACE }}

      - name: Terraform Format
        id: tf-fmt
        working-directory: tests/defaults
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: tf-init
        working-directory: tests/defaults
        run: terraform init -upgrade

      - name: Terraform Validate
        id: tf-validate
        working-directory: tests/defaults
        run: terraform validate

      - name: Terraform Plan
        id: tf-plan
        working-directory: tests/defaults
        run: terraform plan

      - name: Terraform Apply
        id: tf-apply
        working-directory: tests/defaults
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        id: tf-destroy
        working-directory: tests/defaults
        run: terraform apply -destroy -auto-approve